project:
  type: website
  output-dir: _site
  preview:
    port: 3000
    watch-inputs: true

website:
  title: "INTERLIS Transformer"
  site-url: "https://transformer.interlis.guru"
  repo-url: "https://github.com/edigonzales/ilitransformer"
  favicon: assets/img/ilitransformer.png
  navbar:
    pinned: true
    logo: assets/img/ilitransformer.png
    logo-alt: INTERLIS Transformer logo
    search: false
    left:
      - text: Start 
        href: erste_schritte.qmd
      - text: Demo
        href: demo.qmd
      - text: Editor 
        href: editor.qmd
      - text: Referenz
        href: reference/index.qmd
    right:
      - icon: github
        href: https://github.com/edigonzales/ilitransformer
  page-footer:
    left: "Copyright 2026, INTERLIS Transformer contributors"

format:
  html:
    pandoc:
      syntax-definitions:
        - syntax/interlis.xml
        - syntax/ilimap.xml
    theme:
      - default
      - inter-theme.scss
    css: 
      - styles.css
    toc: true
    toc-location: right
    toc-depth: 3
    link-external-newwindow: true
    mainfont: Inter
    code-copy: true
    grid:
      sidebar-width: 290px
      margin-width: 280px
      body-width: 1150px

editor: visual
