services:
  postgis:
    image: sogis/postgis:17-3.6
    container_name: ilitransformer-postgis
    environment:
      POSTGRES_DB: ilitransformer
      POSTGRES_PASSWORD: secret
      POSTGRES_INITDB_ARGS: "-c include_dir=/opt/postgresql/conf.d/"
    ports:
      - "127.0.0.1:54321:5432"
    volumes:
      - type: volume
        source: pgdata_ilitransformer
        target: /var/lib/postgresql/data
      - type: bind
        source: ./initdb/initdb.sh
        target: /docker-entrypoint-initdb.d/initdb.sh
      - type: bind
        source: ./initdb/initdb.sql
        target: /docker-entrypoint-initdb.d/initdb.sql
      - type: bind
        source: ./initdb/postgresql-custom.conf
        target: /opt/postgresql/conf.d/postgresql-custom.conf

    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres -d ilitransformer"]
      interval: 10s
      timeout: 5s
      retries: 5
    restart: unless-stopped

volumes:
  pgdata_ilitransformer:
