package guru.interlis.transformer.cli;

import guru.interlis.transformer.dmav.Direction;
import guru.interlis.transformer.dmav.Dm01DmavPaths;
import guru.interlis.transformer.dmav.MappingCandidateExporter;
import guru.interlis.transformer.dmav.MappingCandidateGenerator;

import java.nio.file.Path;
import java.util.concurrent.Callable;
import picocli.CommandLine.Command;
import picocli.CommandLine.Option;

@Command(
        name = "generate-mapping",
        description = "Generate DM01/DMAV mapping candidates from correlation hints and model inventory",
        mixinStandardHelpOptions = true
)
public final class GenerateMappingCommand implements Callable<Integer> {

    @Option(
            names = {"--hints"},
            required = true,
            description = "Path to correlation-hints.json (generated by import-correlation)"
    )
    private Path hints;

    @Option(
            names = {"--synonyms"},
            description = "Path to synonyms.json"
    )
    private Path synonyms;

    @Option(
            names = {"--out"},
            description = "Output path for mapping-candidates.json (default: build/generated/dm01-dmav/mapping-candidates.json)"
    )
    private Path out = Dm01DmavPaths.GENERATED_CANDIDATES;

    @Option(
            names = {"--report"},
            description = "Output path for candidate report (default: build/reports/dm01-dmav/candidate-report.md)"
    )
    private Path report = Dm01DmavPaths.CANDIDATE_REPORT;

    @Option(
            names = {"--dm01-model"},
            description = "DM01 model name (default: DM01AVCH24LV95D)"
    )
    private String dm01Model = "DM01AVCH24LV95D";

    @Option(
            names = {"--dm01-dir"},
            description = "Model directory for DM01 resolution"
    )
    private String dm01Dir = Dm01DmavPaths.LOCAL_MODEL_DIR;

    @Option(
            names = {"--dmav-model"},
            description = "DMAV model name (default: DMAV_FixpunkteAVKategorie3_V1_1)"
    )
    private String dmavModel = "DMAV_FixpunkteAVKategorie3_V1_1";

    @Option(
            names = {"--dmav-dir"},
            description = "Model directory for DMAV resolution"
    )
    private String dmavDir = Dm01DmavPaths.LOCAL_MODEL_DIR;

    @Option(
            names = {"--yaml-dm01-dmav"},
            description = "Output path for generated DM01→DMAV YAML mapping"
    )
    private Path yamlDm01Dmav = Dm01DmavPaths.GENERATED_DM01_TO_DMAV_YAML;

    @Option(
            names = {"--yaml-dmav-dm01"},
            description = "Output path for generated DMAV→DM01 YAML mapping"
    )
    private Path yamlDmavDm01 = Dm01DmavPaths.GENERATED_DMAV_TO_DM01_YAML;

    @Override
    public Integer call() throws Exception {
        if (!hints.toFile().exists()) {
            System.err.println("Hints file not found: " + hints);
            System.err.println("Run 'import-correlation' first to generate correlation hints.");
            return 1;
        }

        out.getParent().toFile().mkdirs();
        report.getParent().toFile().mkdirs();

        System.out.println("Generating mapping candidates...");
        MappingCandidateGenerator generator = new MappingCandidateGenerator();
        MappingCandidateGenerator.GenerationResult result = generator.generate(
                hints, synonyms, dm01Model, dm01Dir, dmavModel, dmavDir);

        MappingCandidateExporter exporter = new MappingCandidateExporter();
        exporter.writeJson(result.candidates(), out);
        exporter.writeReport(result, report);

        if (dmavModel != null) {
            yamlDm01Dmav.getParent().toFile().mkdirs();
            exporter.writeYaml(result.candidates(), Direction.DM01_TO_DMAV,
                    dm01Model, dmavModel, yamlDm01Dmav);
            exporter.writeYaml(result.candidates(), Direction.DMAV_TO_DM01,
                    dmavModel, dm01Model, yamlDmavDm01);
        }

        System.out.println("Generated " + result.candidates().size() + " mapping candidates");
        System.out.println("  high:   " + result.highCount());
        System.out.println("  medium: " + result.mediumCount());
        System.out.println("  low:    " + result.lowCount());
        System.out.println("  manual: " + result.manualCount());
        System.out.println("  DM01→DMAV: " + result.dm01ToDmavCount());
        System.out.println("  DMAV→DM01: " + result.dmavToDm01Count());

        for (String w : result.warnings()) {
            System.out.println("[WARN] " + w);
        }

        System.out.println("JSON:   " + out);
        System.out.println("Report: " + report);

        return 0;
    }
}
